dist: trusty
os: linux
language: cpp
sudo: required

script:
  - git clone https://code.qt.io/qt/qt5.git
  - cd qt5
  - git checkout 5.11
  - perl init-repository
  - yes | ./configure -opensource -nomake examples -nomake tests
  - make -j4 > null.log

matrix:
  include:
    - env: #COMPILER_NAME=gcc-7 COMPILER_CXX=g++-7 COMPILER_CC=gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ubuntu-sdk-team-ppa
          packages:
            - gcc-7
            - g++-7
            - libsqlite3-dev
            - build-essential
            - libx11-xcb-dev
            - libglu1-mesa-dev
            - perl
            - python
