dist: trusty
os: linux
language: cpp
sudo: required

before_script:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get update -q
  - sudo apt-get install -y qt510-meta-full
  - sudo apt-get install -y libasan0 libubsan0 libtsan0

script:
  # normal
  - mkdir build && cd build
  - source /opt/qt510/bin/qt510-env.sh
  - qmake "QMAKE_CXXFLAGS+=-Werror" ../PassDictionary.pro
  - make CC=${COMPILER_CC} CXX=${COMPILER_CXX} LINK=${COMPILER_CXX}
  - cd ..
  
  # asan
  - mkdir build-asan && cd build-asan
  - source /opt/qt510/bin/qt510-env.sh
  - qmake "CONFIG+=address_sanitizer" ../PassDictionary.pro
  - make CC=${COMPILER_CC} CXX=${COMPILER_CXX} LINK=${COMPILER_CXX}
  - cd ..

matrix:
  include:
    - env: COMPILER_NAME=gcc-7 COMPILER_CXX=g++-7 COMPILER_CC=gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7

    - env: COMPILER_NAME=clang-5.0 COMPILER_CXX=clang++-5.0 COMPILER_CC=clang-5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - gcc-7
            - g++-7
            - clang-5.0
            - clang++-5.0

    - env: COMPILER_NAME=clang-4.0 COMPILER_CXX=clang++-4.0 COMPILER_CC=clang-4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - gcc-7
            - g++-7
            - clang-4.0
            - clang++-4.0
