dist: trusty
os: linux
language: cpp
sudo: required

script:
  - wget http://download.qt.io/official_releases/qt/5.11/5.11.0/qt-opensource-linux-x64-5.11.0.run
  - chmod +x qt-opensource-linux-x64-5.11.0.run
  - ./qt-opensource-linux-x64-5.11.0.run --script qt-installer-noninteractive.qs
  - mkdir build
  - cd build
  - qmake ../PassDictionary.pro
  - make CC=${COMPILER_CC} CXX=${COMPILER_CXX} LINK=${COMPILER_CXX}

matrix:
  include:
    - env: COMPILER_NAME=gcc-7 COMPILER_CXX=g++-7 COMPILER_CC=gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - ubuntu-sdk-team-ppa
          packages:
            - gcc-7
            - g++-7
            - libsqlite3-dev
            - build-essential
            - libx11-xcb-dev
            - libglu1-mesa-dev
            - perl
            - python
