dist: trusty
os: linux
language: cpp
sudo: required

script:
  - mkdir build
  - cd build
  - source /opt/qt510/bin/qt510-env.sh
  - qmake ../PassDictionary.pro
  - make CC=${COMPILER_CC} CXX=${COMPILER_CXX} LINK=${COMPILER_CXX}

matrix:
  include:
    - env: COMPILER_NAME=gcc-7 COMPILER_CXX=g++-7 COMPILER_CC=gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - beineri/opt-qt-5.10.1-trusty
          packages:
            - gcc-7
            - g++-7
            - qt510-meta-full
              #            - qtbase5-dev
              #            - qtdeclarative5-dev
              #            - libqt5webkit5-dev
              #            - libsqlite3-dev
              #            - qt5-default
              #            - qttools5-dev-tools

              #    - env: COMPILER_NAME=clang-5.0 COMPILER_CXX=clang++-5.0 COMPILER_CC=clang-5.0
              #      addons:
              #        apt:
              #          sources:
              #            - ubuntu-toolchain-r-test
              #            - llvm-toolchain-trusty-5.0
              #            - beineri/opt-qt511-trusty
              #          packages:
              #            - gcc-7
              #            - g++-7
              #            - clang-5.0
              #            - clang++-5.0
              #            - qtbase5-dev
              #            - qtdeclarative5-dev
              #            - libqt5webkit5-dev
              #            - libsqlite3-dev
              #            - qt5-default
              #            - qttools5-dev-tools
              #
              #    - env: COMPILER_NAME=clang-4.0 COMPILER_CXX=clang++-4.0 COMPILER_CC=clang-4.0
              #      addons:
              #        apt:
              #          sources:
              #            - ubuntu-toolchain-r-test
              #            - llvm-toolchain-trusty-4.0
              #            - beineri/opt-qt511-trusty
              #          packages:
              #            - gcc-7
              #            - g++-7
              #            - clang-4.0
              #            - clang++-4.0
              #            - qtbase5-dev
              #            - qtdeclarative5-dev
              #            - libqt5webkit5-dev
              #            - libsqlite3-dev
              #            - qt5-default
              #            - qttools5-dev-tools
